name: se3_labs
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - numpy>=1.24.0
  - pandas>=2.0.0
  - pillow>=10.0.0
  - tqdm>=4.66.0
  - pip
  - tensorflow>=2.15.0
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - scikit-learn>=1.3.0
